# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blog_post.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'blog_post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62log_post.proto\x12\x12website_content.v1\x1a\x0c\x63ommon.proto\"\x9c\x01\n\x08\x42logPost\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\x05title\x18\x02 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12/\n\x07\x65xcerpt\x18\x03 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12$\n\x03\x63ta\x18\x04 \x01(\x0b\x32\x17.website_content.v1.CTAB\\\n\x16\x63om.website_content.v1B\rBlogPostProtoP\x01Z1example.com/website_content/v1;website_content_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blog_post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.website_content.v1B\rBlogPostProtoP\001Z1example.com/website_content/v1;website_content_v1'
  _globals['_BLOGPOST']._serialized_start=54
  _globals['_BLOGPOST']._serialized_end=210
# @@protoc_insertion_point(module_scope)
