# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x12website_content.v1\"\x19\n\nI18nString\x12\x0b\n\x03key\x18\x01 \x01(\t\"F\n\x05Image\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x30\n\x08\x61lt_text\x18\x02 \x01(\x0b\x32\x1e.website_content.v1.I18nString\"@\n\x03\x43TA\x12,\n\x04text\x18\x01 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12\x0b\n\x03uri\x18\x02 \x01(\t\"q\n\x0bTitledBlock\x12-\n\x05title\x18\x01 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12\x33\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32\x1e.website_content.v1.I18nStringBZ\n\x16\x63om.website_content.v1B\x0b\x43ommonProtoP\x01Z1example.com/website_content/v1;website_content_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.website_content.v1B\013CommonProtoP\001Z1example.com/website_content/v1;website_content_v1'
  _globals['_I18NSTRING']._serialized_start=36
  _globals['_I18NSTRING']._serialized_end=61
  _globals['_IMAGE']._serialized_start=63
  _globals['_IMAGE']._serialized_end=133
  _globals['_CTA']._serialized_start=135
  _globals['_CTA']._serialized_end=199
  _globals['_TITLEDBLOCK']._serialized_start=201
  _globals['_TITLEDBLOCK']._serialized_end=314
# @@protoc_insertion_point(module_scope)
