# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contact_form_config.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'contact_form_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ontact_form_config.proto\x12\x12website_content.v1\"d\n\x11\x43ontactFormConfig\x12\x17\n\x0f\x66orm_action_uri\x18\x01 \x01(\t\x12\x1b\n\x13success_message_key\x18\x02 \x01(\t\x12\x19\n\x11\x65rror_message_key\x18\x03 \x01(\tBe\n\x16\x63om.website_content.v1B\x16\x43ontactFormConfigProtoP\x01Z1example.com/website_content/v1;website_content_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_form_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.website_content.v1B\026ContactFormConfigProtoP\001Z1example.com/website_content/v1;website_content_v1'
  _globals['_CONTACTFORMCONFIG']._serialized_start=49
  _globals['_CONTACTFORMCONFIG']._serialized_end=149
# @@protoc_insertion_point(module_scope)
