# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_item.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'nav_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enav_item.proto\x12\x12website_content.v1\x1a\x0c\x63ommon.proto\"^\n\x07NavItem\x12-\n\x05label\x18\x01 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12\x0c\n\x04href\x18\x02 \x01(\t\x12\x16\n\x0e\x61nimation_hint\x18\x03 \x01(\t\"8\n\nNavigation\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.website_content.v1.NavItemB[\n\x16\x63om.website_content.v1B\x0cNavItemProtoP\x01Z1example.com/website_content/v1;website_content_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nav_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.website_content.v1B\014NavItemProtoP\001Z1example.com/website_content/v1;website_content_v1'
  _globals['_NAVITEM']._serialized_start=52
  _globals['_NAVITEM']._serialized_end=146
  _globals['_NAVIGATION']._serialized_start=148
  _globals['_NAVIGATION']._serialized_end=204
# @@protoc_insertion_point(module_scope)
