[project]
name = "landing-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "clang-format>=20.1.7",
    "grpcio",
    "grpcio-tools",
    "protobuf",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"] # Pyflakes, pycodestyle (E/W), isort
ignore = ["E402", "E501"] # Ignore line too long errors

[tool.ruff]
line-length = 88
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "generated", # Exclude generated protobuf files
]

# Optional: configure isort if needed, though defaults are often fine
# [tool.ruff.isort]
# known-first-party = ["my_project_module_name"] # If you have local modules

# Optional: configure the formatter if you plan to use `ruff format`
# [tool.ruff.format]
# quote-style = "double"
# indent-style = "space"
# skip-magic-trailing-comma = false
# line-ending = "auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true # For libraries that might not have stubs, like bs4 initially
exclude = ["generated/", "venv/", ".venv/"] # Exclude generated files and virtual envs

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

# If bs4 continues to cause issues even with ignore_missing_imports,
# you might need to specify per-module settings or install stubs if available.
# [[tool.mypy.overrides]]
# module = "bs4"
# ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["."]
python_classes = "TestBuildScript"
