# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testimonial_item.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'testimonial_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16testimonial_item.proto\x12\x12website_content.v1\x1a\x0c\x63ommon.proto\"\xa0\x01\n\x0fTestimonialItem\x12,\n\x04text\x18\x01 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12.\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x1e.website_content.v1.I18nString\x12/\n\x0c\x61uthor_image\x18\x03 \x01(\x0b\x32\x19.website_content.v1.ImageBc\n\x16\x63om.website_content.v1B\x14TestimonialItemProtoP\x01Z1example.com/website_content/v1;website_content_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testimonial_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.website_content.v1B\024TestimonialItemProtoP\001Z1example.com/website_content/v1;website_content_v1'
  _globals['_TESTIMONIALITEM']._serialized_start=61
  _globals['_TESTIMONIALITEM']._serialized_end=221
# @@protoc_insertion_point(module_scope)
