// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "feature_item.proto" (package "website_content.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { TitledBlock } from "./common";
/**
 * @generated from protobuf message website_content.v1.FeatureItem
 */
export interface FeatureItem {
  /**
   * @generated from protobuf field: website_content.v1.TitledBlock content = 1
   */
  content?: TitledBlock; // Optional: Add if icons or specific images per feature are needed
  // string icon_class = 2; // This could be part of a more specific FeatureItem
  // if not all features have it Image image = 3;        // Or an image if
  // preferred over an icon class
}
// @generated message type with reflection information, may provide speed optimized methods
class FeatureItem$Type extends MessageType<FeatureItem> {
  constructor() {
    super("website_content.v1.FeatureItem", [
      { no: 1, name: "content", kind: "message", T: () => TitledBlock },
    ]);
  }
  create(value?: PartialMessage<FeatureItem>): FeatureItem {
    const message = globalThis.Object.create(this.messagePrototype!);
    if (value !== undefined)
      reflectionMergePartial<FeatureItem>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: FeatureItem
  ): FeatureItem {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* website_content.v1.TitledBlock content */ 1:
          message.content = TitledBlock.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.content
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: FeatureItem,
    writer: IBinaryWriter,
    options: BinaryWriteOptions
  ): IBinaryWriter {
    /* website_content.v1.TitledBlock content = 1; */
    if (message.content)
      TitledBlock.internalBinaryWrite(
        message.content,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message website_content.v1.FeatureItem
 */
export const FeatureItem = new FeatureItem$Type();
