name: Lint HTML and CSS

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.html'
      - '**.css'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.html'
      - '**.css'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: github/super-linter@v6 # Updated to v6
        env:
          # HTML and CSS linting are enabled by default.
          # Stylelint will use .stylelintrc.json
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
