name: Lint HTML and CSS

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.html'
      - '**.css'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.html'
      - '**.css'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint HTML
        uses: super-linter/super-linter@v7.4.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          directory: '.' # Directory containing HTML files
          exclude_files: '' # Comma-separated list of files to exclude
          exclude_patterns: '' # Comma-separated list of glob patterns to exclude

      - name: Lint CSS
        uses: yokturmak/stylelint-action@v1.0.2
        with:
          files: '**/*.css' # Glob pattern for CSS files
          config: | # Optional: inline stylelint config
            {
              "extends": "stylelint-config-standard"
            }
