name: Lint HTML and CSS

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.html'
      - '**.css'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.html'
      - '**.css'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint HTML
        uses: anmol098/w3c-html-validator@v1.1.1
        with:
          directory: '.' # Directory containing HTML files
          exclude_files: '' # Comma-separated list of files to exclude
          exclude_patterns: '' # Comma-separated list of glob patterns to exclude

      - name: Lint CSS
        uses: yokturmak/stylelint-action@v1.0.2
        with:
          files: '**/*.css' # Glob pattern for CSS files
          config: | # Optional: inline stylelint config
            {
              "extends": "stylelint-config-standard"
            }
